apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-svc-keycloak
  labels:
    app: app-svc-keycloak
spec:
  selector:
    matchLabels:
      app: app-svc-keycloak
  template:
    metadata:
      labels:
        app: app-svc-keycloak
    spec:
      containers:
        - name: app-svc-keycloak
          image: b3cecchini/app-svc-keycloak:latest
          imagePullPolicy: Always
          args: ["start", "--optimized"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: admin-username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: admin-password
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: db-host
            # - name: KC_DB_URL_PORT
            #   valueFrom:
            #     secretKeyRef:
            #       name: kc-secrets
            #       key: db-port
            # - name: KC_DB_URL_DATABASE
            #   valueFrom:
            #     secretKeyRef:
            #       name: kc-secrets
            #       key: db-name
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: db-username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: db-password
            - name: KC_PROXY_HEADERS
              value: forwarded
            - name: KC_HOSTNAME
              value: https://login.ftown.dev
            - name: KC_HOSTNAME_ADMIN
              value: https://login.ftown.dev
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_TRANSACTION_XA_ENABLED
              value: "false"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-keycloak
  labels:
    app: app-svc-keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: app-svc-keycloak
  type: ClusterIP
