apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-svc-customer
  namespace: default
  labels:
    app: om-svc-customer
spec:
  selector:
    matchLabels:
      app: om-svc-customer
  template:
    metadata:
      labels:
        app: om-svc-customer
    spec:
      containers:
        - name: om-svc-customer
          image: b3cecchini/om-svc-customer:latest
          imagePullPolicy: Always
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-customer
            - name: ConnectionStrings__RedisCache
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: redis-cache
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: om-svc-customer
  labels:
    app: om-svc-customer
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: om-svc-customer
