apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-svc-order
  namespace: default
  labels:
    app: om-svc-order
spec:
  selector:
    matchLabels:
      app: om-svc-order
  template:
    metadata:
      labels:
        app: om-svc-order
    spec:
      containers:
        - name: om-svc-order
          image: b3cecchini/om-svc-order:latest
          imagePullPolicy: Always
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-order
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: om-svc-order
  labels:
    app: om-svc-order
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: om-svc-order
