apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-svc-gateway
spec:
  selector:
    matchLabels:
      app: om-svc-gateway
  template:
    metadata:
      labels:
        app: om-svc-gateway
    spec:
      containers:
        - name: om-svc-gateway
          image: b3cecchini/om-svc-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: om-svc-gateway
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: om-svc-gateway
